# inspired by: 
# https://github.com/orgs/community/discussions/22183#discussioncomment-6321583
# https://github.com/orgs/community/discussions/22183#discussioncomment-8735650

name: cleanup-toolbox-workshop-template
run-name: cleanup-toolbox-workshop-template

on:
  create:

concurrency:
  group: first-time-setup
  cancel-in-progress: true

permissions:
  actions: write
  checks: write
  contents: write

jobs:
  cleanup-toolbox-workshop-template:
    # ensure run only once, when repo generated
    # https://github.com/JetBrains/intellij-platform-plugin-template/blob/main/.github/workflows/template-cleanup.yml
    if: github.event.repository.name != 'template_test'

    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      # Cleanup project
      - name: Cleanup
        run: |
            mv README.md notes.md
            rm -rf .github
            rm -f environment.yml
            touch README.md
            NAME="${GITHUB_REPOSITORY##*/}"
            echo "# $NAME" >> README.md
            echo "Generated from [toolbox-workshop-protocol-template](https://github.com/pep-dortmund/toolbox-workshop-protocol-template)" >> README.md
            echo "Find more information in [notes.md](notes.md)." >> README.md

      # save changed files
      - name: Commit changed files
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Setup repo"

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
